In [33]:
import numpy as np
filename = '/Volumes/Extreme_SSD/mvts_transformer/experiments/ten_tasks_contact_free/attack_at_beginning_and_halfway_hijacking/user1_legitimate/attack_at_beginning_and_halfway_hijacking_user1_fragment_length_100/test_results.npz'
data = np.load(filename, allow_pickle=True)
lst = data.files
print(lst)

['target_masks', 'targets', 'predictions', 'metrics', 'IDs']


In [34]:
import torch
import numpy as np
predictions = torch.from_numpy(np.concatenate(data['predictions'], axis=0))
probs = torch.nn.functional.softmax(predictions)  # (total_samples, num_classes) est. prob. for each class and sample
predictions = torch.argmax(probs, dim=1).cpu().numpy()  # (total_samples,) int class index for each sample
probs = probs.cpu().numpy()

/var/folders/rr/c6bzrfyd5tv0pt24ky9_l4d40000gn/T/ipykernel_71208/923225844.py:4: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  probs = torch.nn.functional.softmax(predictions)  # (total_samples, num_classes) est. prob. for each class and sample


In [35]:
print(probs)

[[0.9758278  0.02417226]
 [0.98996955 0.01003049]
 [0.9547918  0.04520818]
 ...
 [0.9242295  0.07577059]
 [0.9307782  0.06922178]
 [0.9405035  0.05949658]]


In [36]:
print(predictions)

[0 0 0 ... 0 0 0]


In [37]:
targets = torch.from_numpy(np.concatenate(data['targets'], axis=0))
targets = targets.cpu().numpy()
print(targets)

[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


In [38]:
from scipy import io
io.savemat('predictions.mat', {"predictions": predictions })
io.savemat('targets.mat', {"targets": targets })